# Generated by Django 3.1.4 on 2021-01-12 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kitchen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kitchen_name', models.CharField(max_length=100)),
                ('kitchen_logo', models.ImageField(upload_to='images/kitchenlogo')),
                ('about', models.TextField(blank=True, null=True)),
                ('contact', models.BigIntegerField(blank=True, null=True)),
                ('mail', models.EmailField(blank=True, max_length=254, null=True)),
                ('address_line_1', models.CharField(blank=True, max_length=500, null=True)),
                ('address_line_2', models.CharField(blank=True, max_length=500, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('fb_link', models.URLField(blank=True, null=True)),
                ('insta_link', models.URLField(blank=True, null=True)),
                ('kitchen_latitude', models.FloatField(blank=True, null=True)),
                ('kitchen_longitude', models.FloatField(blank=True, null=True)),
                ('gmap_address', models.TextField(blank=True, null=True)),
                ('cover_radius_in_kms', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Closed', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='KitchenGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/gallery')),
            ],
        ),
        migrations.CreateModel(
            name='KitchenRatingsAndReviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratings', models.IntegerField(default=0)),
                ('reviews', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('item_description', models.TextField(blank=True, null=True)),
                ('item_price', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Timing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(blank=True, choices=[('Saturday', 'Saturday'), ('Friday', 'Friday'), ('Wednesday', 'Wednesday'), ('Monday', 'Monday'), ('Sunday', 'Sunday'), ('Thursday', 'Thursday'), ('Tuesday', 'Tuesday')], max_length=100, null=True)),
                ('from_hour', models.TimeField()),
                ('to_hour', models.TimeField()),
                ('kitchen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.kitchen')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_price', models.FloatField()),
                ('quantity', models.FloatField()),
                ('total', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('New Order', 'New Order'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled')], default='New Order', max_length=100)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.menuitem')),
                ('kitchen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.kitchen')),
            ],
        ),
    ]
