# Generated by Django 3.1.4 on 2021-03-06 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20210113_0022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=500)),
                ('message', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='timing',
            name='weekday',
            field=models.CharField(blank=True, choices=[('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Wednesday', 'Wednesday'), ('Tuesday', 'Tuesday'), ('Monday', 'Monday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=100, null=True),
        ),
    ]
