# Generated by Django 3.1.4 on 2021-03-14 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20210306_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Preparing', 'Preparing'), ('On The Way', 'On The Way'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled')], default='New Order', max_length=100),
        ),
        migrations.AlterField(
            model_name='timing',
            name='weekday',
            field=models.CharField(blank=True, choices=[('Friday', 'Friday'), ('Sunday', 'Sunday'), ('Tuesday', 'Tuesday'), ('Monday', 'Monday'), ('Saturday', 'Saturday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday')], max_length=100, null=True),
        ),
    ]
