# Generated by Django 3.1.4 on 2020-12-29 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20201229_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_thumbnail',
        ),
    ]
