# Generated by Django 3.1.4 on 2020-12-29 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_category_category_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchen',
            name='kitchen_latitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kitchen',
            name='kitchen_longitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
