# Generated by Django 3.1.4 on 2020-12-29 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20201230_0438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchen',
            name='kitchen_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kitchen',
            name='kitchen_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
