# Generated by Django 3.1.4 on 2021-03-14 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20210314_2302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='item',
            new_name='items',
        ),
        migrations.AlterField(
            model_name='timing',
            name='weekday',
            field=models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Friday', 'Friday'), ('Wednesday', 'Wednesday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday'), ('Thursday', 'Thursday'), ('Tuesday', 'Tuesday')], max_length=100, null=True),
        ),
    ]
