# Generated by Django 3.1.4 on 2021-01-05 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20201230_0505'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchen',
            name='gmap_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
