# Generated by Django 3.1.4 on 2021-01-06 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_kitchen_gmap_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchen',
            name='cover_radius',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
