# Generated by Django 3.1.4 on 2021-03-14 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20210314_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertotal',
            name='item_order',
            field=models.ManyToManyField(blank=True, null=True, to='base.Order'),
        ),
        migrations.AlterField(
            model_name='timing',
            name='weekday',
            field=models.CharField(blank=True, choices=[('Wednesday', 'Wednesday'), ('Friday', 'Friday'), ('Tuesday', 'Tuesday'), ('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Thursday', 'Thursday'), ('Saturday', 'Saturday')], max_length=100, null=True),
        ),
    ]
