# Generated by Django 3.1.4 on 2021-01-07 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20210106_0627'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchen',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Closed', max_length=100),
        ),
    ]
