# Generated by Django 3.1.4 on 2021-03-14 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20210315_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='timing',
            name='weekday',
            field=models.CharField(blank=True, choices=[('Thursday', 'Thursday'), ('Wednesday', 'Wednesday'), ('Sunday', 'Sunday'), ('Tuesday', 'Tuesday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Monday', 'Monday')], max_length=100, null=True),
        ),
    ]
