# Generated by Django 3.1.4 on 2021-01-08 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_kitchen_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Saturday', 'Saturday'), ('Friday', 'Friday'), ('Sunday', 'Sunday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday')], max_length=100, null=True)),
                ('from_hour', models.TimeField()),
                ('to_hour', models.TimeField()),
                ('kitchen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.kitchen')),
            ],
        ),
    ]
