# Generated by Django 3.1.4 on 2021-03-14 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20210315_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertotal',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Preparing', 'Preparing'), ('On The Way', 'On The Way'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled'), ('Payment Incomplete', 'Payment Incomplete')], default='Payment Incomplete', max_length=100),
        ),
        migrations.AlterField(
            model_name='timing',
            name='weekday',
            field=models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Saturday', 'Saturday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Sunday', 'Sunday'), ('Tuesday', 'Tuesday'), ('Friday', 'Friday')], max_length=100, null=True),
        ),
    ]
