# Generated by Django 3.1.4 on 2021-03-14 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_auto_20210315_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertotal',
            name='payment_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ordertotal',
            name='payment_request_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='timing',
            name='weekday',
            field=models.CharField(blank=True, choices=[('Friday', 'Friday'), ('Thursday', 'Thursday'), ('Wednesday', 'Wednesday'), ('Tuesday', 'Tuesday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday'), ('Monday', 'Monday')], max_length=100, null=True),
        ),
    ]
