# Generated by Django 3.1.4 on 2021-01-10 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20210110_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='kitchen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.kitchen'),
        ),
        migrations.AlterField(
            model_name='timing',
            name='weekday',
            field=models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Wednesday', 'Wednesday'), ('Friday', 'Friday'), ('Tuesday', 'Tuesday'), ('Sunday', 'Sunday'), ('Thursday', 'Thursday'), ('Saturday', 'Saturday')], max_length=100, null=True),
        ),
    ]
