# Generated by Django 3.1.4 on 2021-03-15 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20210315_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertotal',
            name='item_order',
            field=models.ManyToManyField(blank=True, to='base.Order'),
        ),
        migrations.AlterField(
            model_name='timing',
            name='weekday',
            field=models.CharField(blank=True, choices=[('Friday', 'Friday'), ('Tuesday', 'Tuesday'), ('Monday', 'Monday'), ('Wednesday', 'Wednesday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday'), ('Thursday', 'Thursday')], max_length=100, null=True),
        ),
    ]
