# Generated by Django 3.1.4 on 2021-01-10 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_auto_20210110_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='timing',
            name='weekday',
            field=models.CharField(blank=True, choices=[('Friday', 'Friday'), ('Thursday', 'Thursday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Sunday', 'Sunday'), ('Saturday', 'Saturday'), ('Wednesday', 'Wednesday')], max_length=100, null=True),
        ),
    ]
