# Generated by Django 3.1.4 on 2021-01-12 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_auto_20210110_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timing',
            name='weekday',
            field=models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Friday', 'Friday'), ('Wednesday', 'Wednesday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday'), ('Thursday', 'Thursday')], max_length=100, null=True),
        ),
    ]
