# Generated by Django 3.1.4 on 2020-12-26 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201226_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.BigIntegerField(default=7002821881),
        ),
    ]
