# Generated by Django 3.1.4 on 2020-12-29 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20201226_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(blank=True, default='password', max_length=100, null=True),
        ),
    ]
