# Generated by Django 3.1.4 on 2020-12-29 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20201229_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_location_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_location_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
